/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import processing.core.PApplet;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    public void testInitialize() {
        // test App correctly read in configuration
        App testGameApp = new App();
        PApplet.runSketch(new String[] {"App"}, testGameApp);
        testGameApp.setup();


    }
}
