/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.jupiter.api.Test;
import processing.core.PApplet;
import processing.core.PImage;

import java.security.Permission;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class TestGameManager {
    protected static class ExitException extends SecurityException {
        public final int status;
        public ExitException(int status) {
            this.status = status;
        }
    }

    private static class OverrideExitManager extends SecurityManager {
        @Override
        public void checkPermission(Permission perm) {}
        @Override
        public void checkPermission(Permission perm, Object context) {}

        @Override
        public void checkExit(int exitCode) {
            super.checkExit(exitCode);
            throw new ExitException(exitCode);
        }
    }

    @Test
    public void testInitialize() {
        // test GameManager correctly read in configuration
        GameManager testGhostGame = new GameManager("src/test/resources/test_player_eat.json");
        TestApp testGhostGameApp = new TestApp(testGhostGame);
        PApplet.runSketch(new String[] {"App"}, testGhostGameApp);
        testGhostGameApp.setup();
        testGhostGame.initMap(testGhostGameApp);

        assertEquals(1, testGhostGame.ghosts.size());
        assertEquals(3, testGhostGame.fruits.size());
        assertEquals(3, testGhostGame.player.getLife());
        assertEquals(1, testGhostGame.state);
    }

    // JacocoTestReport does not support this method of overriding System.exit, so it won't be count as my coverage,
    // sad.
    @Test
    public void testErrors() {
        SecurityManager securityManager = System.getSecurityManager();
        System.setSecurityManager(new OverrideExitManager());

        // test json format error
        try {
            GameManager testGhostGame = new GameManager("src/test/resources/test_error_config.json");
        } catch (ExitException e) {
            assertEquals(1, e.status);
        }

        // test json format error
        try {
            GameManager testGhostGame = new GameManager("src/test/resources/test_error_config.json");
        } catch (ExitException e) {
            assertEquals(1, e.status);
        }

        // test json no content
        try {
            GameManager testGhostGame = new GameManager("src/test/resources/test_empty_config.json");
        } catch (ExitException e) {
            assertEquals(1, e.status);
        }
        // test json no map location
        try {
            GameManager testGhostGame = new GameManager("src/test/resources/test_no_map_config.json");
        } catch (ExitException e) {
            assertEquals(1, e.status);
        }
        // test json invalid map location
        try {
            GameManager testGhostGame = new GameManager("src/test/resources/test_invalid_map_config.json");
        } catch (ExitException e) {
            assertEquals(1, e.status);
        }
        // test json invalid map size
        try {
            GameManager testGhostGame = new GameManager("src/test/resources/test_invalid_size_config.json");
        } catch (ExitException e) {
            assertEquals(1, e.status);
        }
        // test json invalid speed
        try {
            GameManager testGhostGame = new GameManager("src/test/resources/test_speed_too_high.json");
        } catch (ExitException e) {
            assertEquals(1, e.status);
        }
        try {
            GameManager testGhostGame = new GameManager("src/test/resources/test_speed_too_low.json");
        } catch (ExitException e) {
            assertEquals(1, e.status);
        }
        // test json no mode length
        try {
            GameManager testGhostGame = new GameManager("src/test/resources/test_no_mode_length.json");
        } catch (ExitException e) {
            assertEquals(1, e.status);
        }
        System.setSecurityManager(securityManager);
    }

    @Test
    public void testStates() {
        // test gameManager.states
        GameManager testGhostGame = new GameManager("src/test/resources/test_player_eat.json");
        TestApp testGhostGameApp = new TestApp(testGhostGame);
        PApplet.runSketch(new String[] {"App"}, testGhostGameApp);
        testGhostGameApp.setup();
        testGhostGame.initMap(testGhostGameApp);
        // win -> reset -> initialize
        testGhostGame.state = 3;
        testGhostGame.draw(testGhostGameApp);
        assertEquals(5, testGhostGame.state);
        testGhostGame.draw(testGhostGameApp);
        assertEquals(0, testGhostGame.state);
        testGhostGame.draw(testGhostGameApp);
        testGhostGame.player.kill();
        testGhostGame.player.kill();
        testGhostGame.player.kill();
        // lose -> reset
        testGhostGame.draw(testGhostGameApp);
        assertEquals(4, testGhostGame.state);
        testGhostGame.draw(testGhostGameApp);
        assertEquals(5, testGhostGame.state);
    }

    @Test
    public void testDebugState() {
        // test game manager able to switch between different debug states
        GameManager testGhostGame = new GameManager("src/test/resources/test_debug.json");
        TestApp testGhostGameApp = new TestApp(testGhostGame);
        PApplet.runSketch(new String[] {"App"}, testGhostGameApp);
        testGhostGameApp.setup();
        List<Ghost> ghostList = testGhostGame.ghosts;
        ghostList.forEach(Ghost::findTarget);
        testGhostGame.keyPressed(32);
        assertEquals(1, testGhostGame.debug);
        for (Ghost ghost : ghostList) {
            testGhostGame.handleDebug(testGhostGameApp, ghost, false);
        }
        testGhostGame.keyPressed(82);
        assertEquals(2, testGhostGame.debug);
        for (Ghost ghost : ghostList) {
            testGhostGame.handleDebug(testGhostGameApp, ghost, false);
        }
        testGhostGame.keyPressed(32);
        assertEquals(0, testGhostGame.debug);
        for (Ghost ghost : ghostList) {
            testGhostGame.handleDebug(testGhostGameApp, ghost, false);
        }
        ghostList.forEach(ghost -> ghost.setState(Ghost.CHASE));
        ghostList.forEach(Ghost::findTarget);
        testGhostGame.keyPressed(82);
        assertEquals(2, testGhostGame.debug);
        for (Ghost ghost : ghostList) {
            testGhostGame.handleDebug(testGhostGameApp, ghost, false);
        }
        testGhostGame.keyPressed(82);
        assertEquals(1, testGhostGame.debug);
        for (Ghost ghost : ghostList) {
            testGhostGame.handleDebug(testGhostGameApp, ghost, false);
        }
        testGhostGame.keyPressed(32);
        assertEquals(0, testGhostGame.debug);

        // when nullGhost is added to the map, the debug mode will not print anything, but the function still works
        testGhostGame = new GameManager("src/test/resources/test_null_ghost.json");
        testGhostGameApp = new TestApp(testGhostGame);
        PApplet.runSketch(new String[] {"App"}, testGhostGameApp);
        testGhostGameApp.setup();
        ghostList = testGhostGame.ghosts;
        ghostList.forEach(Ghost::findTarget);
        testGhostGame.keyPressed(32);
        assertEquals(1, testGhostGame.debug);
        for (Ghost ghost : ghostList) {
            testGhostGame.handleDebug(testGhostGameApp, ghost, false);
        }
        testGhostGame.keyPressed(82);
        assertEquals(2, testGhostGame.debug);
        for (Ghost ghost : ghostList) {
            testGhostGame.handleDebug(testGhostGameApp, ghost, false);
        }
        testGhostGame.keyPressed(32);
        assertEquals(0, testGhostGame.debug);
        for (Ghost ghost : ghostList) {
            testGhostGame.handleDebug(testGhostGameApp, ghost, false);
        }
        ghostList.forEach(ghost -> ghost.setState(Ghost.CHASE));
        ghostList.forEach(Ghost::findTarget);
        testGhostGame.keyPressed(82);
        assertEquals(2, testGhostGame.debug);
        for (Ghost ghost : ghostList) {
            testGhostGame.handleDebug(testGhostGameApp, ghost, false);
        }
        testGhostGame.keyPressed(82);
        assertEquals(1, testGhostGame.debug);
        for (Ghost ghost : ghostList) {
            testGhostGame.handleDebug(testGhostGameApp, ghost, false);
        }
        testGhostGame.updatePlayers(testGhostGameApp);
        testGhostGame.keyPressed(32);
        assertEquals(0, testGhostGame.debug);
    }

    @Test
    public void testChangeState() {
        // test updateTimer()
        GameManager testGhostGame = new GameManager("src/test/resources/test_null_ghost.json");
        TestApp testGhostGameApp = new TestApp(testGhostGame){
            @Override
            public int millis() {
                return 10000;
            }
            public final int frameCount = 0;
        };
        PApplet.runSketch(new String[] {"App"}, testGhostGameApp);
        testGhostGameApp.setup();
        try {
            Thread.sleep(100);
        } catch (InterruptedException ignored) {
        }
        testGhostGame.startTime = 0;
        boolean result = testGhostGame.updateTimer(testGhostGameApp);
        assertEquals(10000, testGhostGame.startTime);
        assertTrue(result);
        testGhostGame.modePointer = 0;
        testGhostGame.startTime = 0;

        // test updatePlayers change state
        testGhostGame.ghosts = new ArrayList<>();
        Ghost newGhost = new NullGhost(new PImage[]{null, null}) {
            @Override
            public void findTarget() {
                this.target = new MapCell(null, 7, 9, 0);
                super.findTarget();
            }
        };
        testGhostGame.ghosts.add(newGhost);
        testGhostGame.updatePlayers(testGhostGameApp);
        assertEquals(Ghost.CHASE, newGhost.state);
        testGhostGame.updatePlayers(testGhostGameApp);
        assertEquals(144, newGhost.target.x);
        assertEquals(0, newGhost.target.y);
        testGhostGame.startTime = 0;
        testGhostGame.updatePlayers(testGhostGameApp);
        assertEquals(Ghost.SCATTER, newGhost.state);
        testGhostGame.modePointer = 0;
        testGhostGame.startTime = 0;

        // test updatePlayers change previous tate
        newGhost.frighten();
        testGhostGame.updatePlayers(testGhostGameApp);
        assertEquals(Ghost.CHASE, newGhost.previousState);
        testGhostGame.startTime = 0;
        testGhostGame.updatePlayers(testGhostGameApp);
        assertEquals(Ghost.SCATTER, newGhost.previousState);
        testGhostGame.modePointer = 0;
        testGhostGame.startTime = 0;
    }
}
